# Generated by Django 5.2 on 2026-03-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Mediem', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In_progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentupdate',
            name='update_type',
            field=models.CharField(choices=[('Comment', 'Comment'), ('Status_Change', 'Status Change'), ('Assignment', 'Assignment'), ('Resolution', 'Resolution')], max_length=20),
        ),
        migrations.AlterField(
            model_name='slatracking',
            name='sla_status',
            field=models.CharField(choices=[('Safe', 'Safe'), ('Warning', 'Warning'), ('Breached', 'Breached')], default='SAFE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Engineer', 'Engineer'), ('Support', 'Support')], default='ADMIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='ACTIVE', max_length=20),
        ),
    ]
