# Generated by Django 5.2 on 2026-03-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_incident_priority_alter_incident_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('eEngineer', 'Engineer'), ('support', 'Support')], default='ADMIN', max_length=20),
        ),
    ]
