# Generated by Django 5.2 on 2026-03-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('engineer', 'Engineer'), ('support', 'Support')], default='ADMIN', max_length=20),
        ),
    ]
