# Generated by Django 5.2 on 2026-03-07 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebase',
            name='related_incidents',
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='auto_resolve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='category',
            field=models.CharField(blank=True, choices=[('Setup', 'Setup'), ('Troubleshooting', 'Troubleshooting'), ('FAQ', 'FAQ'), ('Network', 'Network'), ('Security', 'Security'), ('Performance', 'Performance'), ('Configuration', 'Configuration')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='script_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], default='Draft', max_length=20),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='resolution_steps',
            field=models.TextField(blank=True),
        ),
    ]
