# Generated by Django 5.2 on 2026-03-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_knowledgebase_related_incidents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Pending', 'Pending Approval')], default='Draft', max_length=20),
        ),
    ]
