# Generated by Django 5.2 on 2026-03-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_knowledgebase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('INCIDENT_ASSIGNED', 'Incident Assigned'), ('SLA_WARNING', 'SLA Warning'), ('INCIDENT_RESOLVED', 'Incident Resolved'), ('KNOWLEDGE_SUBMITTED', 'Knowledge Submitted'), ('KNOWLEDGE_APPROVED', 'Knowledge Approved'), ('KNOWLEDGE_REJECTED', 'Knowledge Rejected')], max_length=50),
        ),
    ]
