# Generated by Django 5.2 on 2026-03-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('mediem', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
