# Generated by Django 5.2 on 2026-03-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_incident_priority_alter_incident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentupdate',
            name='update_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('status_Change', 'Status Change'), ('assignment', 'Assignment'), ('resolution', 'Resolution')], max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='category',
            field=models.CharField(blank=True, choices=[('setup', 'Setup'), ('troubleshooting', 'Troubleshooting'), ('faq', 'FAQ'), ('network', 'Network'), ('security', 'Security'), ('performance', 'Performance'), ('configuration', 'Configuration')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('pending', 'Pending Approval')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='slatracking',
            name='sla_status',
            field=models.CharField(choices=[('safe', 'Safe'), ('warning', 'Warning'), ('breached', 'Breached')], default='SAFE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('engineer', 'Engineer'), ('support', 'Support')], default='Admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
