# Generated by Django 5.2 on 2026-03-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_incidentactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='incident_attachments/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolution_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
