# Generated by Django 5.2 on 2026-03-09 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_incident_attachment_incident_closed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentupdate',
            old_name='comment',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='incidentupdate',
            name='update_type',
        ),
        migrations.RemoveField(
            model_name='incidentupdate',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='incidentupdate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
