# Generated by Django 5.2 on 2026-03-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_user_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('pending', 'Pending Approval')], default='draft', max_length=20),
        ),
    ]
