# Generated by Django 5.2 on 2026-03-17 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_knowledgebase_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.knowledgebase'),
        ),
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, help_text='Store additional context like IDs, names, etc.', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_DELETED', 'User Deleted'), ('USER_ACTIVATED', 'User Activated'), ('USER_DEACTIVATED', 'User Deactivated'), ('INCIDENT_CREATED', 'Incident Created'), ('INCIDENT_ASSIGNED', 'Incident Assigned'), ('INCIDENT_RESOLVED', 'Incident Resolved'), ('INCIDENT_SENT_FOR_VERIFICATION', 'Incident Sent For Verification'), ('INCIDENT_REOPENED', 'Incident Reopened'), ('INCIDENT_CLOSED', 'Incident Closed'), ('ARTICLE_CREATED', 'Article Created'), ('ARTICLE_SUBMITTED_FOR_APPROVAL', 'Article Submitted For Approval'), ('ARTICLE_APPROVED', 'Article Approved'), ('ARTICLE_REJECTED', 'Article Rejected'), ('ARTICLE_PUBLISHED', 'Article Published'), ('SLA_WARNING', 'SLA Warning')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='user_notifi_user_id_c3061c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event_type'], name='user_notifi_event_t_2781e1_idx'),
        ),
    ]
