# Generated by Django 5.2 on 2026-03-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_notification_options_notification_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
